[platformio]
default_envs = megaatmega2560

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

; Serial Monitor options
monitor_speed = 115200

;extra_scripts = post_build.py
;targets = disasm
